### ISSUE TITLE
First time run behaviour when config entry doesn't exist

### ISSUE THREAD

**Issue by owenherbert** [catalyst/moodle-block_dedication#105]
If the database table `prefix_config_plugins` does not contain the `lastcalculated` named entry the `dedication_collector` task will behave as if it were being run the for the first time, each run.

**Comment by danmarsden** [comment]
Thanks Owen! - I was thinking about this the other day and thought we should just move this block:
https://github.com/catalyst/moodle-block_dedication/blob/MOODLE_400_STABLE/classes/lib/utils.php#L268-L270

outside the if (!empty($records)) call - that way when no records are returned - we still store the last run time so it doesn't try and re-process that timeframe again.

**Comment by danmarsden** [comment]
thanks @owenherbert!
