### ISSUE TITLE
Información de todos los grupos accesible a un usuario profesor no edición que está asignado a solo un grupo

### ISSUE THREAD

**Issue by rmartinez-c2** [catalyst/moodle-block_dedication#107]
Buenos días.

No sé si es por la configuración del usuario o de vuestro plugin pero no soy capaz de crear un usuario supervisor (profesor sin edición) asignado a un grupo y que solo vea el tiempo de dedicación de dicho curso. Sí es verdad que, automáticamente, la vista se filtra con su grupo pero sigue teniendo la opción de quitar dicho filtro y ver toda la información de los participantes. ¿Alguna idea?

Moodle: 4.0.6 (Build: 20230116)
Block dedication: 2023112000

Gracias.

Saludos.

**Comment by danmarsden** [comment]
there was an issue with separate groups that was fixed back in 3adea8938ce604d03b28ad202f4e63fb53ab610a but check to make sure you have separate groups enabled within the course and that the users you are trying to restrict don't have the accessallgroups capability.

also... I don't support Moodle 4.0 anymore (neither does Moodle HQ) so you should really be upgrading your moodle release as well.

**Comment by rmartinez-c2** [comment]
Acabo de revisar todo y, después de configurar el curso con grupos separados, de inicio, el usuario supervisor solo ve su grupo pero, si utiliza los filtros, puede seguir viendo todos los participantes. ¿Esto es normal?

**Comment by danmarsden** [comment]
could be a bug in there with the way filters are applied especially if the user doesn't have moodle/site:accessallgroups' 

I couldn't reproduce it myself on a recent Moodle release but either it's an issue with Moodle 4.0 which I no longer support or I've not quite managed to reproduce the exact conditions you have.

If you have internal development capabilities and manage to track down the issue feel free to submit a PR with a fix for me to review.

**Comment by rmartinez-c2** [comment]
He desarrollado un parche para que el filtro de grupos solo se muestre en cursos con grupos visibles o para usuarios con permisos para ver todos los grupos. Solo hay que cambiar el método **add_filters** de **classes/local/systemreports/course.php** por

```
    protected function add_filters(): void {
        $filters = [
            'user:fullname',
            'dedication:timespent',
        ];
        
        global $PAGE, $USER;
        if ($PAGE->course->groupmode == VISIBLEGROUPS || has_capability('moodle/site:accessallgroups', $PAGE->context)) {
            $filters[] = 'groups:group';
        }

        $this->add_filters_from_entities($filters);
    }
```
