### ISSUE TITLE
Enlace paginación erróneo

### ISSUE THREAD

**Issue by rmartinez-c2** [catalyst/moodle-block_dedication#110]
Buenos días.

Acabo de detectar que los enlaces de paginación del reporte de un usuario es incorrecto. El enlace que se muestra es URL_MOODLE/?page=x cuando debería ser URL_MOODLE/blocks/dedication/user.php?id=zzz&userid=yyy&page=x

![01  Enlace paginación erróneo](https://github.com/catalyst/moodle-block_dedication/assets/3283956/07bd64d1-7085-4aa8-a66e-0f3d5c2702a7)

Lo mismo ocurre con el listado de usuarios, no pagina bien.

Moodle: 4.3.3+ (Build: 20240409)
Block dedication: 2023112000

Gracias.

Saludos.

**Comment by danmarsden** [comment]
Moodle's pagination at the code level starts at page "0" which is visually represented to the end user as the first page.

When you hit Page "2" are you not seeing the 2nd set of results?

**Comment by rmartinez-c2** [comment]
Lo que he comentado anteriormente no es del todo cierto, lo siento.

La url se forma como comentaba pero la paginación funciona correctamente para la tabla de dedicación de todos los usuarios. Sin embargo, para la tabla de dedicación de un usuario, nunca me muestra resultados a excepción de la primera página. Cuando pulso en la segunda (o tercera) página me dice que no hay nada que mostrar. Sin embargo, si escribo manualmente la url (URL_MOODLE/blocks/dedication/user.php?id=zzz&userid=yyy&page=x), la página se carga correctamente con los datos que debe mostrar.

Espero haberme explicado mejor.

Muchas gracias.

**Comment by danmarsden** [comment]
thanks for the clarification - That page works fine for me in Chrome and Moodle's standard themes - the pagination occurs using a JS process - can you check your browser console to see if any javascript errors are occurring on the page?

**Comment by rmartinez-c2** [comment]
No veo ningún error en consola que pudiera afectar. El problema ocurre tanto en Chrome como en Firefox. No he probado más navegadores. ¿Alguna idea más?

**Comment by danmarsden** [comment]
try clearing cache, turning cachejs off, try using a core theme if you are using a custom one, also try the other system reports to see if they page correctly like the task logs report - if you have issues on other system reports it's an issue with your site - not the dedication plugin.

I've just tested this again on a 4.3 vanilla site with the dedication block and I can't reproduce the issue.

**Comment by rmartinez-c2** [comment]
Puedo aportar más información.

He probado con los temas Moove, Boost y Trema y el error sigue existiendo.

Con la siguentes versiones, funciona correctamente con todos los temas:
Moodle: 4.0.6 (Build: 20230116)
Block dedication: 2023112000

La paginación en otras páginas y otros sistemas de registro, funcionan correctamente. Solo he detectado el error en la tabla de dedicación de un usuario del bloque de dedicación.

@danmarsden , ¿con qué versión del bloque de dedicación has realizado tus pruebas, con la 2023112000 o con la 2023112001?

Muchas gracias.

**Comment by rmartinez-c2** [comment]
Con la versión 2023112001 este error no se da.

Gracias por todo.

Saludos.
