### ISSUE TITLE
Access to courses with this plugin (downloaded from here on 16 Dec 2022) is broken

### ISSUE THREAD

**Issue by pejhab** [catalyst/moodle-block_dedication#67]
I downloaded the plugin from a couple of days ago and installed it on my Moodle 4.1 website.

Now I can no-longer access the courses that contain this block.

I get the following error message:

_Error
Error reading from database
Debug info: Table 'ppph_21moodle.mdl_block_dedication' doesn't exist
SELECT SUM(timespent)
FROM mdl_block_dedication
WHERE courseid = ? AND userid = ?
[array (
0 => '75',
1 => '2',
)]
Error code: dmlreadexception
Stack trace:

    line 494 of /lib/dml/moodle_database.php: dml_read_exception thrown
    line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
    line 1278 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->query_end()
    line 1679 of /lib/dml/moodle_database.php: call to mysqli_native_moodle_database->get_records_sql()
    line 1752 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
    line 280 of /blocks/dedication/classes/lib/utils.php: call to moodle_database->get_field_sql()
    line 67 of /blocks/dedication/block_dedication.php: call to block_dedication\lib\utils::timespent()
    line 337 of /blocks/moodleblock.class.php: call to block_dedication->get_content()
    line 231 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
    line 1222 of /lib/blocklib.php: call to block_base->get_content_for_output()
    line 1280 of /lib/blocklib.php: call to block_manager->create_block_contents()
    line 377 of /lib/blocklib.php: call to block_manager->ensure_content_created()
    line 4085 of /lib/outputrenderers.php: call to block_manager->region_has_content()
    line 53 of /theme/boost/layout/drawers.php: call to core_renderer->blocks()
    line 1473 of /lib/outputrenderers.php: call to include()
    line 1399 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
    line 236 of /course/view.php: call to core_renderer->header()_

**Comment by danmarsden** [comment]
Thanks for testing the new version! - we missed the upgrade script required to add the new table which I've just added into the latest version here in github - hopefully that should fix that particular issue but let us know if you find any other problems!

thanks,

**Comment by pejhab** [comment]
I have installed the new version. So far, so good.
