### ISSUE TITLE
Report not showing at all

### ISSUE THREAD

**Issue by Trystan-SA** [catalyst/moodle-block_dedication#68]
Until yesterday, we used version 3.x+ (2020041000) from the moodle.org plugin directory. But for some reason, the old report was crashing for some courses (not all), and since I could not isolate what went wrong, we decided to update this plugin directly from this repo (Moodle 4.X - c371aab from 20 December). We use Moodle 4.1.1+ (build 20230120).

The report from "**site administration --> Report --> Dedication report**" return a 404 url not found error.

The settings from "**admin/settings.php?section=blocksettingdedication**" are all on default values.

When I try to access the _full report_ from this plugin's block ( "**blocks/dedication/index.php?id=COURSEID**" ) it says "Nothing to show". The filters are also set to default.

I tried to access this block directly from a student's account (connect as) and an error is raised, probably because students can't access this data by default.

The students all have logs attached to their accounts. So I'm not quite sure what is the issue here. Any ideas ?

**Comment by danmarsden** [comment]
Hi Trystan, 
If you take a look at the README here in github it states "Timespent information is now generated via a scheduled task" - this means that your cron/scheduled task processes must be running and it generates that data overnight.

I'll look at seeing if we can add a useful error message if someone installs the plugin and views a report before that task runs for the first time.

**Comment by Trystan-SA** [comment]
Hi danmarshden.

Yes that was the issue 😅. Maybe a button that regenerates the full report manually could also fix this issue ? I'm glad the report is back like before. We almost had to calculate it back manually, you saved us a lot of administrative work ! Thanks a lot 👍
