### ISSUE TITLE
Course name and Group name fields - report columns

### ISSUE THREAD

**Issue by ecerda** [catalyst/moodle-block_dedication#69]
Is it possible to add the course name and group name fields as a report column ({BASE_URL}/blocks/dedication/index.php?id={COURSE_ID})? It would be great!

Related PR: https://github.com/catalyst/moodle-block_dedication/pull/65

**Comment by danmarsden** [comment]
Thanks @ecerda yes, group support is coming - it's the main thing blocking the release to the plugins db - that patch is close but isn't quite ready yet and we hope to get it sorted soon.

The reportbuilder source for dedication already includes support for all course fields so you can create a custom report in the site that includes course name, but we don't plan to add it to the /index.php "system report" becuase this report is course specific, - it only shows the current courses dedication information. If you are not familiar with Moodle's new report builder tool - try creating a new custom report using the dedication report source included in this plugin and you should be able to see how to add course name there.
