### ISSUE TITLE
Wrong string identifier

### ISSUE THREAD

**Issue by drobayo** [catalyst/moodle-block_dedication#72]
Hello Catalyst team.

First of all, thank you very much for this great addition and effort put into your update.

We have found a small bug in the definition of the text strings:
https://github.com/catalyst/moodle-block_dedication/blob/MOODLE_400_STABLE/lang/en/block_dedication.php#L57
`$string['privacy:metadata'] = 'The block_dedication plugin stores times users have dedicated to courses.';`

Since the definition of this string, and where it is used, is as follows:
https://github.com/catalyst/moodle-block_dedication/blob/MOODLE_400_STABLE/classes/privacy/provider.php#L55
`'privacy:metadata:block_dedication'`

Fix:
https://github.com/catalyst/moodle-block_dedication/blob/MOODLE_400_STABLE/lang/en/block_dedication.php#L57
`$string['privacy:metadata:block_dedication'] = 'The block_dedication plugin stores times users have dedicated to courses.';`

It is not something that stops the plugin from working so I don't think it is urgent but it would be good to avoid the warning.

Thanks Catalyst team.

**Comment by danmarsden** [comment]
Thanks for the report! - I've dropped a fix into the privacy class - I didn't change the string identifier as that would mean anyone that has already translated it would need to do it again.

Let us know if you find any other issues!

thanks,
