### ISSUE TITLE
Display username and email in file export

### ISSUE THREAD

**Issue by mcruzel** [catalyst/moodle-block_dedication#74]
Hello,

In the previous version, i did this because my dean of studies wanted to use xls exports with other data (in pivot table).
https://github.com/IOC/moodle-block_dedication/pull/1

Is there an easy way to implement (maybe optional) display of email adress and eventually username in the xlsx exports of a course dedication ?

Thank you in advance.

Best regards.

Maxime Cruzel
Digital Learning Manager

**Comment by danmarsden** [comment]
Try using the custom report source built into this plugin which let's you design a report with a wide range of columns.. under admin > reports > custom reports.

**Comment by danmarsden** [comment]
closing this for now as it's something that is supported in the custom reports - but please let me know if there are further improvements that would be good to add.
