### ISSUE TITLE
invalidparameter creating custom report

### ISSUE THREAD

**Issue by leonstr** [catalyst/moodle-block_dedication#75]
Steps to reproduce issue:
1. Go to **Site administration** > **Reports** > **Report builder** > **Custom reports**
2. Click **New report**.
3. Type a name, select **Report source:** "Dedication: Users Dedication", and click **Save**.

Expected results:
New report is created.

Actual results:
invalidparameter
Invalid parameter value detected
File: ...es/local/helpers/report.php
Line: 114
Stack trace:
```
Invalid column
Error code: invalidparameter
* line 114 of /reportbuilder/classes/local/helpers/report.php: invalid_parameter_exception thrown
* line 94 of /reportbuilder/classes/datasource.php: call to core_reportbuilder\local\helpers\report::add_report_column()
* line 58 of /reportbuilder/classes/local/helpers/report.php: call to core_reportbuilder\datasource->add_default_columns()
* line 130 of /reportbuilder/classes/form/report.php: call to core_reportbuilder\local\helpers\report::create_report()
* line 77 of /lib/form/classes/external/dynamic_form.php: call to core_reportbuilder\form\report->process_dynamic_submission()
* line 261 of /lib/externallib.php: call to core_form\external\dynamic_form::execute()
* line 81 of /lib/ajax/service.php: call to external_api::call_external_function()
```

Using block_dedication 2023031700 (6f6f325) with Moodle 4.1.3+ (Build: 20230526) or Moodle 4.2+ (Build: 20230512). Stack trace is from Moodle 4.1.3+.

**Comment by leonstr** [comment]
I can get the report to be created by editing `classes/reportbuilder/datasource/user_dedication.php` changing line 86 to:

```
        return ['user:fullname', 'user:username', 'dedication:timespent'];
```
and line 104 to:

```
        return [];
```

**Comment by danmarsden** [comment]
Thanks for all the reports and the suggested fixes! - I'll work through these and tidy some of this up!!
