### ISSUE TITLE
"Warning: The time spent calculation task is not running regularly" always displayed

### ISSUE THREAD

**Issue by leonstr** [catalyst/moodle-block_dedication#77]
After the `\block_dedication\task\dedication_collector` scheduled task has first run the block always displays the message _Warning: The time spent calculation task is not running regularly_.

**Comment by leonstr** [comment]
Surely line 72 of `block_dedication.php` should be:

```
        if ($lastruntime < time() - (2 * DAYSECS)) {
```

I.e. if the last run time is before (less than) than two days ago?

**Comment by danmarsden** [comment]
hmm - surprised that hasn't been noticed/reported before... I also note that it's not really looking at the best value there - $lastruntime is not the last time that task ran but is the last time it collected data, which could be even older. We should adjust that to use the cron task timing instead too.

**Comment by danmarsden** [comment]
I decided we don't really even need this warning at the block level - it's not something we should be warning students/teachers about so it doesn't make a lot of sense in the block.. I did leave the warning in place when the task has never run as that will help with admins/first time install and testing.
