### ISSUE TITLE
Group mode: Separate groups not respected

### ISSUE THREAD

**Issue by leonstr** [catalyst/moodle-block_dedication#78]
With course settings _Group mode_: "Separate groups" I would not expect teachers in one group to see students in another. However when the teacher clicks on _Full report_ in the block (`blocks/dedication/index.php?id=XYZ`) they see course participants from all groups.

This was previously reported in #45 which was closed. With "Separate groups" selected ["each group can only see their own group – other groups are invisible"](https://docs.moodle.org/402/en/Groups_FAQ#What_is_the_.27groups_mode.27_setting.3F). Is it intentional that this block will ignore this group mode?

**Comment by danmarsden** [comment]
not intentional - probably a bug with the new groups code handling on that system report - thanks for the report - feel free to submit a PR with a fix if you manage to find some time and work out where the issue is.

**Comment by danmarsden** [comment]
in fact - I thought we'd fixed separate groups handling in https://github.com/catalyst/moodle-block_dedication/commit/3adea8938ce604d03b28ad202f4e63fb53ab610a

can you confirm which version of the plugin you were using when you saw this issue? and that the users you were testing with don't have the accessallgroups capability in the course?

**Comment by leonstr** [comment]
You're correct, this is fixed.

I'd forgotten that the Teacher (editingteacher) role has moodle/site:accessallgroups.

I've re-tested as a Non-editing teacher (teacher) and the contents of the table on blocks/dedication/index.php?id=?? shows only participants in the same group as expected.

Apologies for the error.

**Comment by danmarsden** [comment]
great thanks for confirming that and with your help in testing/reporting the other issues you found!
