### ISSUE TITLE
Moodle version support?

### ISSUE THREAD

**Issue by Frostist** [catalyst/moodle-block_dedication#81]
Hi, does this plugin support Moodle 4.2?

I see from the main page it doesn't support it, when will it?

**Comment by danmarsden** [comment]
this page: https://moodle.org/plugins/block_dedication/stats 

shows there are over 100 registered 4.2 sites using the plugin - and I can't see any reports in the tracker reporting issues with it - feel free to try it and report any issues you find to the tracker :-)

**Comment by Frostist** [comment]
Thanks man! 

Another question... once the plug-in is installed... where am I meant to actually use it? I have gone into courses, but I see no functionality?

**Comment by danmarsden** [comment]
It's a "block" plugin, so you could add the dedication block to a course which would expose some links, but it also includes a report builder source so you can create your own reports using it under admin > reports > custom reports.
