### ISSUE TITLE
The user sessions report should be ordered by timestart and not by id

### ISSUE THREAD

**Issue by marcoblancas** [catalyst/moodle-block_dedication#86]
I don't know why in our mdl_block_dedication table there was a gap with some days and I run this in command to collect data session that were missing.

`sudo -u www-data php recalculate.php --start=1694500662 --end=1694736073`

The problem is that these sessions are displayed at the end of the report. You can see in this screen capture.

![2023-09-21_16-24](https://github.com/catalyst/moodle-block_dedication/assets/5545390/a01fcbd9-4836-4285-a713-f8971cd67971)

I suppose the report is ordering by id records from mdl_block_dedication and maybe is better to order by timestart

**Comment by danmarsden** [comment]
thanks for the report - yeah, sounds like the default ordering on the system report page needs fixing - pull requests are always welcome too! :-)
