### ISSUE TITLE
After installing Course Dedication version 2023070300 on Moodle 4.3 (Build: 20231009), the 'Course Dedication' option cannot be found in the dashboard and courses interface.

### ISSUE THREAD

**Issue by weisy0629** [catalyst/moodle-block_dedication#88]
After installing Course Dedication version 2023070300 on Moodle 4.3 (Build: 20231009), the 'Course Dedication' option cannot be found in the dashboard and courses interface.

**Comment by danmarsden** [comment]
This is a block plugin. Once you have installed the code you need to add it to the pages where you want to display it. See https://docs.moodle.org/403/en/Blocks

**Comment by weisy0629** [comment]
Thanks a lot, I found it.

But I still&nbsp;
However, I encountered a new issue on the Linux system where the cron is running, but it simply displays 'Time spent calculation task has not run yet.' How can this be resolved? Thank you againt.









                       
Original Email
                       
                     

Sender:"Dan Marsden"< ***@***.*** &gt;;

Sent Time:2023/10/14 16:15

To:"catalyst/moodle-block_dedication"< ***@***.*** &gt;;

Cc recipient:"weisy0629"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [catalyst/moodle-block_dedication] After installing CourseDedication version 2023070300 on Moodle 4.3 (Build: 20231009), the 'CourseDedication' option cannot be found in the dashboard and courses interface.(Issue #88)




 
This is a block plugin. Once you have installed the code you need to add it to the pages where you want to display it. See https://docs.moodle.org/403/en/Blocks

**Comment by danmarsden** [comment]
probably best to ask for further help in the community forums on moodle.org - the github issues trackers for our plugins are for reporting bugs - not for asking help with using Moodle or plugins. all the best!
