### ISSUE TITLE
Revertir versión

### ISSUE THREAD

**Issue by rmartinez-c2** [catalyst/moodle-block_dedication#89]
Hola de nuevo.

Actualmente, acabo de actualizar a la versión 2023070300 de vuestro plugin en un moodle 4.0.6 (Build: 20230116). Después de ver su funcionamiento, veo que varias cosas no funcionan del todo bien y otras se han cambiado a peor.

¿Sería posible volver vuestro plugin a la versión anterior que tenía?

Gracias.

Saludos.

**Comment by danmarsden** [comment]
Hi there - thanks for the feedback. As mentioned in the [README ](https://github.com/catalyst/moodle-block_dedication/blob/MOODLE_400_STABLE/README.md) the previous version of the plugin had some signficant short-comings and bugs that meant we had to change some of the way the plugin operated, and as we were limited by the funding available to do this work we had to make some design decisions that initially limited some of the functionality available in the new version. We would definitely love to improve this and return some of the functionality - in particular the ability to run the stats collection task more frequently. If you have internal development capabilities then pull requests are always very welcome - alternatively if you would like to fund the development required to improve the plugin further please reach out and we can provide information on our rates.

thanks!

**Comment by rmartinez-c2** [comment]
Vale, lo entiendo pero, ¿es posible desinstalar vuestro plugin de la version 2023070300 e instalar el plugin de una versión anterior sin problemas?

**Comment by danmarsden** [comment]
That's not something we can help with but the easiest way for you to do it would be to completely delete the block and trigger the uninstall process in the admin plugins page to delete all instances of the block on your site - then add back the old version - keep in mind that it's not tested in newer versions and contains a large number of bugs that the new version of the plugin resolves. Good luck!
