### ISSUE TITLE
add ability to sort "session time" field in custom report source.

### ISSUE THREAD

**Issue by azimshaikh95** [catalyst/moodle-block_dedication#90]
Moodle Custom Report using **Dedication** as data source,

The following features not working
-Conditions 
-Sorting 
-Card view 

I can sort report by course name or user name
but I want it to be sort by Session Time, which is not available.

**Comment by danmarsden** [comment]
Hi there - what version of Moodle are you using? - some of these issues don't sound like they are specific to the dedication data source but may be issues with your theme or with the core reportsource features - have you tried using sorting/card-view on other reports in your site?

**Comment by azimshaikh95** [comment]
Hi There, I'm using Moodle 4.3 latest release.
I tried the other data sources, they support Sorting and filter. But dedication block it's not working

**Comment by danmarsden** [comment]
Ah - the duration field in the report is a bit custom and yes, it does not currently support sorting - if you have internal development capabilities, feel free to submit a PR to improve this.

I've just pushed a fix for the conditions not loading, but the "card view" issue you mention seems to work fine to me - when I make the page with smaller, it converts to card view fine.

**Comment by azimshaikh95** [comment]
1.

![image](https://github.com/catalyst/moodle-block_dedication/assets/35104251/c69cba4a-9535-4de3-adb7-a1915a0f3699)

Also, the duration field is displayed in "## hours ## mins ## sec", Is is possible to get it in a single unit? like "## hours" (even with floating point numbers) or "## mins".

Because, we can't sort this. so when we export it into excel, we cant directly sort there also.
If in a single unit then it will be easy to sort and find analyze the results

2. Can't add dedication block on frontpage of your Moodle site. I want it to be added on each course. So geenrally follow the steps mentioned here.
[https://createdbycocoon.com/knowledge/adding-block-all-courses-moodle](https://createdbycocoon.com/knowledge/adding-block-all-courses-moodle
)
But I'm unable to add block on site home.

**Comment by danmarsden** [comment]
@azimshaikh95 - can you please make sure you create new tracker issues when discussing separate issues? - it just helps to keep the thread clear. :-)  - although, don't worry about creating one for the site home issue - I created #94 for that (and just pushed a fix that might sort that for you.)

Excel can definitely sort that field - just do some google searching on how to handle durations in excel - if that doesn't throw anything up - look at the special date handling options and you should be able to find a way to sort that in excel.

In terms of adding a single unit field - sure, anything is possible (create a new tracker issue for the request) - but keep in mind feature development time is very hard for me to find unless someone is paying for the time for a developer to implement it (It's hard enough keeping on top of all the email/messaging comms let alone finding time for "free" feature development!) :-)

**Comment by azimshaikh95** [comment]
Thanks a lot for the fix of issue #94. I will keep into mind creating a new tracker for future issues.

**Comment by azimshaikh95** [comment]
Hi @danmarsden ,
Thanks for the guidance. I just updated Pull Request with **Added Sorting in sessionduration and sessionstart both columns**

**Comment by danmarsden** [comment]
Thanks for the report - I believe these issues have now been resolved in the latest version here in github (this hasn't been released into the plugins db yet) - if you get a chance, please test the version here in github and let us know if you have any issues with the changes.
