### ISSUE TITLE
Export to .CSV and .XLSX on user report downloads current logged in user and not selected user.

### ISSUE THREAD

**Issue by evilforces** [catalyst/moodle-block_dedication#98]
When exporting the data to .CSV or .XLSL format, not all the content that appears on the student page within Moodle is exported.

The export only exports part of the data or even exports data from a student other than the one currently appearing on the screen.

**Comment by evilforces** [comment]
This is an example of exporting a student's times.

As can be seen, the screen times in Moodle do not match the data exported to Excel

![2023-11-21_07h34_31](https://github.com/catalyst/moodle-block_dedication/assets/9539744/64ccc603-d650-499a-af65-53a56a553557)
![2023-11-21_07h34_43](https://github.com/catalyst/moodle-block_dedication/assets/9539744/86610464-6f89-4fe4-a9a8-befc960e2521)

The exported data belongs to the course teacher and not the student. Here you can see the teacher's connection data.

![2023-11-21_07h39_18](https://github.com/catalyst/moodle-block_dedication/assets/9539744/615fd873-26a2-4e9b-89b0-46994e113a7b)

**Comment by rmartinez-c2** [comment]
Hola.

En algún hilo de este proyecto, comentaron cómo solucionar este problema. Al menos a mi me ha funcionado:

En **user.php** hay que pasar parámetros de curso y usuario tal y como se indica en la documentación del método system_report_factory::create :

`$params = ['courseid' => $courseid, 'userid' => $userid];
$report = system_report_factory::create(userreport::class, context_course::instance($courseid), '', '',
0, $params);`

En classes/local/systemreports/userreport.php, recogemos el parámetro userid pasado por el método system_report_factory::create en dedication/user.php, del que hemos hablado anteriormente:
`$userid = $this->get_parameter('userid', 0, PARAM_INT);`

@evilforces , creo que con estos dos cambios, se soluciona tu problema

Saludos.

**Comment by danmarsden** [comment]
Thanks @rmartinezgc - I took a quick look back at the code earlier today and noticed the same issue. Feel free to drop in a PR with the fix otherwise I'll try to get that fixed later this week.
